process_names:
  - comm:
    - sshd
    - cadvisor
    - node_exporter
    - ntpd

  - exe: ["/usr/bin/python2"]
    cmdline: ["/usr/bin/fail2ban-server"]
    name: fail2ban

  - exe: ["/usr/sbin/syslog-ng"]
    name: syslog-ng

  - exe: ["process_exporter"]
    name: process_exporter

  - exe: ["dockerd"]
    name: dockerd

  - exe: ["docker-containerd"]
    name: containerd
